Array - pascal triangle
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #275
Opened 2022-03-13 18:15 UTC by DevratAgarwal

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-18 02:54 UTC, sailesh-ramayanam commented
@satya-9 
1. Write a function that takes an integer value n as input and prints ~first n lines~ `n`th line of the Pascal’s triangle.
2. Please format `n`, wherever it appears
3. `n` is written in lower case in the description and in upper case in input/output format. Please use same case everywhere.

2022-03-18 03:06 UTC, sailesh-ramayanam requested changes
@DevratAgarwal 
1. Please remove other files from this PR
2. Please address my comments below
3. Some of the comments are applicable to your other PRs as well. Please make changes wherever applicable.

2022-03-18 03:06 UTC, sailesh-ramayanam commented on solutions/arrays/pascal-triangle.js
> +	let arr=[1]
Rename `arr` to `prevRow`

2022-03-18 03:06 UTC, sailesh-ramayanam commented on solutions/arrays/pascal-triangle.js
> +		let temporaryArray=[]
Rename `temporaryArray` to `currRow`

2022-03-18 03:06 UTC, sailesh-ramayanam commented on solutions/arrays/pascal-triangle.js
> +			if(column===1)
Always use curly braces , even for single line body. Apply this wherever applicable in  this program as well as in your other PRs.

2022-03-19 17:39 UTC, DevratAgarwal commented
@sailesh-ramayanam @satya-9 changes are addressed

2022-03-20 05:35 UTC, LVSsandeepVarma commented
@sailesh-ramayanam  updated the problem description

2022-03-20 05:54 UTC, LVSsandeepVarma approved these changes

2022-03-20 10:46 UTC, prathyusha10x commented
@sailesh-ramayanam please review the updated code and approve the PR by today EOD

2022-03-22 06:29 UTC, sailesh-ramayanam approved these changes

2022-03-22 06:29 UTC, merged