Array - matrix diagonal
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #279
Opened 2022-03-13 18:22 UTC by DevratAgarwal

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-18 03:58 UTC, sailesh-ramayanam commented
@satya-9 
1. Variable names in the template code can be better
2. Strings are not converted to integers

2022-03-18 04:18 UTC, sailesh-ramayanam requested changes

2022-03-18 04:18 UTC, sailesh-ramayanam commented on solutions/arrays/matrix-diagonal.js
> +		for(let column=0;column<arr.length;column++)
@DevratAgarwal This is O(n^2) time. We don't need a nested loop. We can do in O(n) time.

2022-03-19 17:41 UTC, DevratAgarwal commented
@sailesh-ramayanam @satya-9 changes are addressed

2022-03-20 06:26 UTC, LVSsandeepVarma commented
> 

@sailesh-ramayanam  , @DevratAgarwal  updated the template code

2022-03-21 13:55 UTC, sailesh-ramayanam approved these changes

2022-03-21 13:57 UTC, merged