Array - good pairs
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #283
Opened 2022-03-13 18:35 UTC by DevratAgarwal

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-18 05:22 UTC, sailesh-ramayanam requested changes

2022-03-18 05:22 UTC, sailesh-ramayanam commented on solutions/arrays/good-pairs.js
> +	for(let index1=index+1;index1<arr.length;index1++)
@DevratAgarwal Please rename `index` to `focusedIndex` and `index1` to `comparedIndex`.

2022-03-19 17:43 UTC, DevratAgarwal commented
@sailesh-ramayanam @satya-9 changes are addressed

2022-03-20 11:09 UTC, prathyusha10x commented
@sailesh-ramayanam @LVSsandeepVarma please review the updated code and approve the PR by tomorrow EOD

2022-03-21 14:22 UTC, sailesh-ramayanam approved these changes

2022-03-21 14:22 UTC, merged