Array - rotate matrix
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #284
Opened 2022-03-13 18:46 UTC by DevratAgarwal

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-17 07:39 UTC, rpapavan97 approved these changes
1. Added ";" at the end of each line
2. Modified the logic to complete the rotating in one nested loop instead of two nested loops (previously)
3. Added spaces around the binary operators

2022-03-18 05:36 UTC, sailesh-ramayanam commented
@rpapavan97 Output explanation uses the term `transpose`. We are not doing a transpose. Please remove the term.

2022-03-18 05:41 UTC, sailesh-ramayanam requested changes

2022-03-18 05:41 UTC, sailesh-ramayanam commented on solutions/arrays/rotate-matrix.js
> +	console.log(arr[0].length);
@DevratAgarwal Please do not print inside this function. Read about single responsibility principle. Perhaps we can avoid writing a function.

2022-03-18 12:57 UTC, rpapavan97 commented
@sailesh-ramayanam updated the Explanation section in problem

2022-03-19 17:44 UTC, DevratAgarwal commented
@rpapavan97 @sailesh-ramayanam changes are addressed

2022-03-20 11:10 UTC, prathyusha10x commented
@rpapavan97 @sailesh-ramayanam please review the code and approve the PR by tomorrow EOD

2022-03-21 14:07 UTC, sailesh-ramayanam commented on solutions/arrays/rotate-matrix.js
> +for(let row=0;row<val;row++)
Rename `row` to `rowIndex`

2022-03-21 14:09 UTC, sailesh-ramayanam commented on solutions/arrays/rotate-matrix.js
> +for(val of out){
Rename `val` to `row`

2022-03-21 14:14 UTC, sailesh-ramayanam commented on solutions/arrays/rotate-matrix.js
> +    }
We don't need 2 sets of nested loops. We can do with 1 set.
```js
for colIndex from 0 to n-1{
    for rowIndex from n-1 to 0 {
         newRow.push(matrix[rowIndex][colIndex])
    }
    roatedMatrix.push(newRow)
}
```

2022-03-21 14:15 UTC, sailesh-ramayanam commented on solutions/arrays/rotate-matrix.js
> +function rotate(lst)
Please don't use a function. Write it as part of the main logic itself.

2022-03-21 17:47 UTC, DevratAgarwal commented
@sailesh-ramayanam done all changes

2022-03-22 02:45 UTC, sailesh-ramayanam approved these changes

2022-03-22 02:46 UTC, merged