Arrays - Sum Of Diagonals
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #303
Opened 2022-03-16 03:27 UTC by Abduliitr

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-16 13:25 UTC, LVSsandeepVarma approved these changes
code looks good , but while working on video, @prathyusha10x make sure that whoever records this video   explain what  `+=`  is , as many students might not know about it

2022-03-18 05:48 UTC, sailesh-ramayanam requested changes

2022-03-18 05:48 UTC, sailesh-ramayanam commented on solutions/arrays/sum-of-diagonals.js
> +    sumSecondDiagonal += matrix[i][j];
@Abduliitr 
1. One for loop is sufficient for both diagonals 
2. No need of `j` - normally I would have preferred the use of `j`. In this case I want the students to see the computation of diagonal indices.

2022-03-19 17:44 UTC, DevratAgarwal commented
@LVSsandeepVarma @sailesh-ramayanam changes are addressed

2022-03-20 11:18 UTC, prathyusha10x commented
@sailesh-ramayanam @LVSsandeepVarma Please review the Updated codes and approve the PR by 21 march 2022

2022-03-23 02:26 UTC, LVSsandeepVarma commented
> @LVSsandeepVarma @sailesh-ramayanam changes are addressed

@DevratAgarwal  I did'nt see any changes in the code , did you commit your changes?

2022-03-23 03:44 UTC, DevratAgarwal commented
@LVSsandeepVarma sorry it was not my question.

2022-03-25 09:38 UTC, sailesh-ramayanam approved these changes

2022-03-25 09:38 UTC, merged