Recursion - Recursive Sequence
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #339
Opened 2022-03-29 17:01 UTC by prateek-mehra

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-30 08:49 UTC, vinthaivendhan10x commented
@LVSsandeepVarma kindly Review

2022-03-30 09:55 UTC, LVSsandeepVarma requested changes
@prateek-mehra  , since we are giving this problem in  recursion topic we need a recursive solution instead of iterative solution

2022-03-30 13:14 UTC, prateek-mehra commented on solutions/recursion/recursive-sequence.js
> +
1. Yes I mentioned **f** for better understanding.

2. Done.

2022-03-31 05:37 UTC, vinthaivendhan10x commented on solutions/recursion/recursive-sequence.js
> +
@LVSsandeepVarma kindly Review

2022-04-02 12:07 UTC, LVSsandeepVarma approved these changes

2022-04-07 03:57 UTC, sailesh-ramayanam requested changes
@prateek-mehra

2022-04-07 03:57 UTC, sailesh-ramayanam commented on solutions/recursion/recursive-sequence.js
> +function f(operands, num, n){
@prateek-mehra 
1. We don't need the parameters `operands` and `num`. Just `n` is sufficient.
2. `currentTerm` will be a product of `n` integers, starting from (n*(n-1)/2)
3. This implementation can be rewritten as `currentTerm + f(n-1)`.
4. Also, please format the code properly. There are extra empty lines, extra indentation etc. If you are using VS Code, you can use the built-in formatter. Right click -> Format Document

2022-04-07 10:30 UTC, vinthaivendhan10x commented
@LVSsandeepVarma kindly Review

2022-04-07 12:00 UTC, sailesh-ramayanam approved these changes

2022-04-07 12:00 UTC, merged