Control Flow - Dice
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #418
Opened 2022-04-20 15:05 UTC by prateek-mehra

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-04-21 05:15 UTC, vinthaivendhan10x commented
@shivateja1729  kindly Review

2022-04-25 03:12 UTC, sailesh-ramayanam requested changes

2022-04-25 03:12 UTC, sailesh-ramayanam commented on solutions/control flow/dice.js
> +numberOnTheBottom = 7 - numberOnTheTopFace;
@prateek-mehra 

1. Please use `let` to declare variables.
2. Please rename the folder to `control-flow`.

2022-04-27 03:24 UTC, sailesh-ramayanam approved these changes

2022-04-27 03:39 UTC, shivateja1729 approved these changes

2022-04-30 14:04 UTC, vinthaivendhan10x commented
@sailesh-ramayanam Merging Pending

2022-05-05 05:53 UTC, merged