Classes - car sale customer
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #91
Opened 2022-03-09 06:49 UTC by Rahulkug

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-09 15:18 UTC, rpapavan97 approved these changes

2022-03-11 08:04 UTC, sailesh-ramayanam requested changes

2022-03-11 08:04 UTC, sailesh-ramayanam commented on solutions/classes/car-sale-customer.js
> +    let flag = false;
@Rahulkug We don't need `count` and `flag`. If there are no promising cutomers, the array will be of `0` length, in which case you can push `-1`

2022-03-11 08:08 UTC, sailesh-ramayanam commented
@rpapavan97 
1. First line contains n, an integer denoting the number of customers ~0<n<=100~ (no need to give the bounds for `n`. some students give unnecessary importance to the bounds and get completely carried away from the main point).
2. Output format is described incorrectly - it should say something like `Each line of output should contain the index of a prospective customer. The indices should be output in ascending order. If there is no prospective customer, output -1.`

2022-03-11 08:33 UTC, rpapavan97 commented
@sailesh-ramayanam , updated the above modifications in problem description

2022-03-15 16:06 UTC, prathyusha10x commented
@sailesh-ramayanam @rpapavan97  rahul made the changes in code please review it once he will start the recording

2022-03-17 04:48 UTC, sailesh-ramayanam approved these changes

2022-03-17 04:48 UTC, merged