Classes- input reader
DSA-solutions-the10xacademy/JavaScript-DSA-Solutions pull request #92
Opened 2022-03-09 06:49 UTC by Rahulkug

## Checklist
- Solution is tested on sphere engine <br/>
    `Note:` Please copy only the solution part. Do not copy/paste the template code. That way, any issues with template code can be caught early on.
    - [ ] Author
    - [ ] Reviewer
- PR title is correct - [PR title conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#title-for-a-pull-request)
    - [ ] Author
    - [ ] Reviewer
- Folder/File naming is correct - [Naming conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#naming-of-files-and-folders)
    - [ ] Author
    - [ ] Reviewer
- Coding conventions are followed - [Coding conventions](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions)
    - [ ] Author
    - [ ] Reviewer
- Test cases (action item for **reviewer**) <br/>
    - To be ensured by checking the problem on sphere-engine
    - If any test cases are missing, please add them - [how to add new test cases](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#adding-new-test-cases)
    - [ ] There are at least 2 test cases
    - [ ] There is at least 1 test case that is different from the sample test cases

2022-03-09 12:09 UTC, shivateja1729 commented on solutions/classes/input-reader.js
> +const Inputreader = class {
[naming conventions ](https://github.com/DSA-solutions-the10xacademy/JavaScript-DSA-Solutions#coding-conventions) are not full filled with variable, function and class names.  like `Inputreader`  `Data`  `read_integers` `read_strings`  `typeofinput ` etc.,

2022-03-09 12:09 UTC, shivateja1729 commented on solutions/classes/input-reader.js
> +    new Inputreader(i).read_strings();
I think its better to store the instance of the class as a class variable first, and then use it everytime.
like `let NewInputReader = new InputReader(i)`. Please correct me if its not a good practice of storing as variables.

2022-03-10 07:11 UTC, shivateja1729 commented on solutions/classes/input-reader.js
> +    new Inputreader(i).read_strings();
> 

@sailesh-ramayanam  should i make the above change in the code?

2022-03-10 09:07 UTC, shivateja1729 approved these changes

2022-03-11 09:02 UTC, sailesh-ramayanam requested changes

2022-03-12 06:30 UTC, shivateja1729 commented on solutions/classes/input-reader.js
> +}
@sailesh-ramayanam edited the above changes in the code and problem description.

2022-03-12 06:30 UTC, shivateja1729 commented on solutions/classes/input-reader.js
> +    console.log(this.Index + " " + this.data);
@sailesh-ramayanam addressed.

2022-03-12 11:58 UTC, sailesh-ramayanam commented
@shivateja1729 Template is missing.

2022-03-12 16:52 UTC, shivateja1729 commented
> @shivateja1729 Template is missing.

@sailesh-ramayanam  template was not mentioned in problem description. Seems like there is no template for this problem.

2022-03-13 03:25 UTC, sailesh-ramayanam commented
@shivateja1729 We should always provide template for `Functions`, `Classes` and `Linked Lists`. Otherwise, students will simply solve with a for loop without using the relevant concept.

2022-03-13 03:41 UTC, shivateja1729 commented
> @shivateja1729 We should always provide template for `Functions`, `Classes` and `Linked Lists`. Otherwise, students will simply solve with a for loop without using the relevant concept.

@sailesh-ramayanam  added the template and updated the problem statement as per the template.

2022-03-13 03:42 UTC, shivateja1729 commented on solutions/classes/input-reader.js
> +    this.Index = Index;
@sailesh-ramayanam made changes.

2022-03-13 05:45 UTC, sailesh-ramayanam approved these changes

2022-03-13 05:45 UTC, merged